/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yusukekawata' at '16/04/14 10:46' with Gradle 2.4
 *
 * @author yusukekawata, @date 16/04/14 10:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
